apiVersion: v1
kind: Service
metadata:
  name: vprofile-db-service
spec:
  ports:
    - port: 3306        # What the app expects (Internal Pod Port)
      targetPort: 4566  # What MiniStack is actually listening on!
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vprofile-db-service
subsets:
  - addresses:
      - ip: 192.168.49.1  # Your host machine IP link
    ports:
      - port: 4566        # Match the active MiniStack edge channel