apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-app-deployment
  labels:
    app: vprofile-app
spec:
  replicas: 3 # MNC Standard: High Availability. If one container crashes, the others handle traffic.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 # Zero-Downtime: Never take down old containers until new ones are healthy!
  selector:
    matchLabels:
      app: vprofile-app
  template:
    metadata:
      labels:
        app: vprofile-app
    spec:
      containers:
      - name: vprofile-container
        image: localhost:5001/vprofile-app:latest # Pulls directly from the registry you just built!
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi" # Production Safeguard: Prevents container from eating up all VM host memory
          requests:
            cpu: "250m"
            memory: "256Mi"
