apiVersion: v1
kind: Service
metadata:
  name: vprofile-app-service
spec:
  type: NodePort # Exposes the service outside the cluster onto a specific port
  selector:
    app: vprofile-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31000 # Access the live application via http://<VM-IP>:31000
